Build blackbox_exporter with go 1.19.9
prometheus/blackbox_exporter pull request #1066
Opened 2023-05-10 12:32 UTC by electron0zero

Go came out with new secruity release with [fixes for bunch of CVEs](https://go.dev/doc/devel/release#go1.20), Update go to build blackbox_exporter.

Also see #1070

2023-05-10 12:56 UTC, SuperQ commented on go.mod
> +go 1.20
We only update the Go minimum version if required.

2023-05-10 12:56 UTC, SuperQ commented on go.mod
> +	github.com/prometheus/client_golang v1.15.1
We typically let dependabot take care of these things.

2023-05-15 13:39 UTC, SuperQ commented on .circleci/config.yml
> +      - image: cimg/go:1.19.9
We don't ever specify a specific version here, this tag always uses the latest point release. No need to change it.

2023-05-15 13:40 UTC, SuperQ requested changes
These changes don't actually do anything, as the final binary is produced with the Prometheus `golang-builder` docker image. This is controlled via promu.

2023-05-15 15:15 UTC, electron0zero commented
closing this in favor of https://github.com/prometheus/blackbox_exporter/pull/1072

2023-05-15 15:15 UTC, closed without merging