websocket target support
prometheus/blackbox_exporter pull request #1278
Opened 2024-08-11 17:06 UTC by adnull

According to #1081 this change adds websocket target support to monitor availability and functionality of websocket servers. 

This probe provides features as follows:
- Basic HTTP authentification
- Bearer token
- Arbitrary HTTP headers
- Option to skip server certificate checking on connect
- Send/Receive sequences with regexp matching to ensure the server is working correctly ( similar to the TCP probe)

New metrics:
- probe_http_status_code: resulting http status code on connection
- probe_is_upgraded: is the connection successfuly upgraded to a websocket connection
- probe_failed_due_to_regex: 1 when send/receive sequence wasn't matched to server messages

2025-06-06 12:57 UTC, sanya2022 commented
Any updates here?

2025-06-06 13:23 UTC, adnull commented
> Any updates here?

If only.. althrough the year isn't passed yet :)

2025-10-13 12:21 UTC, bilkoua commented
Could you either approve this merge or let us know what needs to be revised?
@electron0zero @SuperQ

2025-10-30 09:58 UTC, electron0zero requested changes

2025-10-30 09:58 UTC, electron0zero commented on config/config.go
> +type WebsocketProbe struct {
can you add tests for the probe config.

2025-10-30 09:58 UTC, electron0zero commented on CONFIGURATION.md
> +### `<tls_config>`
I am bit confused by this change in tls_config, why is this added?

2025-10-30 09:58 UTC, electron0zero commented on example.yml
> +        bearer_token: "secret_token"
does it make sense to configure `bearer_token` and `basic_auth` both? usually you would use one or the other. if you want to show an example of both config, please create two examples instead of putting both in one example.

2025-10-30 09:58 UTC, electron0zero commented on prober/websocket.go
> +		Name: "probe_http_status_code",
```suggestion
		Name: "probe_websocket_status_code",
```

`probe_http_status_code` metric name already exists in http prober.  we have probe_<prober>_status_code metric names, so please follow that.

2025-10-30 09:58 UTC, electron0zero commented on prober/websocket.go
> +		Name: "probe_is_upgraded",
```suggestion
		Name: "probe_websocket_connection_upgraded",
```

please follow `probe_<prober>_` pattern here as well. 

also `is_upgraded` is not very clear on "what" is upgraded, so use `connection_is_upgraded` or `connection_upgraded`

please see https://prometheus.io/docs/practices/naming/ to read more about naming best practices.

2025-10-30 09:58 UTC, electron0zero commented on config/config.go
> +	InsecureSkipVerify bool                   `yaml:"insecure_skip_verify,omitempty"`
`InsecureSkipVerify` is part of tls config, please follow the example of other probe configs and expose full tls_config, like we do it gRPC and other probes.

2025-10-30 09:58 UTC, electron0zero commented on config/config.go
> +type HTTPClientConfig struct {
any reasons to redefine this instead of using `config.HTTPClientConfig` from `github.com/prometheus/common/config` package?

we use it in HTTPProbe so it would be a good idea to use the same struct and keep things common and uniform.

2025-10-30 09:58 UTC, electron0zero commented on config/config.go
> +type HTTPBasicAuth struct {
same comment as HTTPClientConfig, the BasicAuth in the github.com/prometheus/common/config has File support and is more rich, any reasons to NOT use it?

if we use github.com/prometheus/common/config's HTTPClientConfig, we don't need this type.

2025-10-30 09:58 UTC, electron0zero commented on prober/websocket.go
> +		TLSClientConfig: &tls.Config{
once we use the TLSConfig from `github.com/prometheus/common/config`, please configure more fields so end users can control those.

TLS MinVersion and TLS ServerName seems to be something I can think we need to expose but it also make sense to expose CA cert and client cert configs so folks can configure tls for websocket probes.

2025-10-30 09:58 UTC, electron0zero commented on prober/websocket.go
> +			Name: "probe_failed_due_to_regex",
same here, please see metric names in other probers and follow their lead.

2025-10-30 09:58 UTC, electron0zero commented on prober/websocket.go
> +		for _, qr := range module.Websocket.QueryResponse {
nit: this block is deeply nested and hard to read. can you simplify it and make it easier to read please.

2025-10-30 09:59 UTC, electron0zero commented
please rebase with master and resolve conflicts and update the PR desc to follow the new PR template: https://github.com/prometheus/blackbox_exporter/blob/master/.github/PULL_REQUEST_TEMPLATE.md 🙏🏼

2025-10-30 18:52 UTC, adnull commented on prober/websocket.go
> +			Name: "probe_failed_due_to_regex",
```suggestion
			Name: "probe_websocket_failed_due_to_regex",
```

2025-11-02 13:38 UTC, adnull commented on config/config.go
> +type HTTPClientConfig struct {
config.HTTPClientConfig is used to construct new http client using prometheus internal functions while I need to create a custom Dialer with a set of http headers to establish a connection. I still don't see any way to create raw headers from it, so it needs a third-party implementation to provide full support of the config options (including password files etc).  That's why I made my own config structure.

2025-11-10 09:25 UTC, bilkoua commented
@adnull Could you bring the pull request up to date so it can be merged into master? Do you need any help with that?

2025-11-10 11:14 UTC, adnull commented
@bilkoua Hi! Will do shortly.

2025-12-05 10:13 UTC, bilkoua commented
@adnull any updates? Do you need any help with that?

2025-12-05 19:59 UTC, adnull commented
@bilkoua Just rebased on master, fixed suggested things, except using standart http and tls config structures. I can't use prometheus HTTPConfig as TLSConfig as they are only used in prometheus functions and probes whereas I need to make Dialer myself and I'm only able to pass headers into it, so it needs additional implementation to construct headers from prometheus config structures if we want to use it.

2025-12-08 18:50 UTC, bilkoua commented
@adnull Thank you very much. Could you also fix `ci/circleci: test `and `DCO`? Without that, it’s unlikely we’ll be able to proceed with the pull request.

2025-12-08 21:29 UTC, adnull commented
@bilkoua Sure, fixed the things

2025-12-11 12:52 UTC, bilkoua commented
@electron0zero Could you take a look at this PR after the changes?

2026-01-01 10:46 UTC, electron0zero requested changes

2026-01-01 10:46 UTC, electron0zero commented on example.yml
> +
```suggestion
```

trim this line and add the missing newline at the end of file

2026-01-01 10:46 UTC, electron0zero commented on CONFIGURATION.md
> +
you should link to example.yaml for examples and add all the examples in one place (example.yml), only add the config options exposed by the websocket probe in this page.

2026-01-01 10:46 UTC, electron0zero commented on CONFIGURATION.md
> +### `<tls_config>`
can you address this requested change? this looks like a duplicate of the existing `<tls_config>` section

2026-01-01 10:46 UTC, electron0zero commented on CONFIGURATION.md
> +[ http_config: <websocket_http_config>]
seems like a stray change? can you remove it?

2026-01-01 10:46 UTC, electron0zero commented on CONFIGURATION.md
> +#### `<oauth2>`
can this be removed as well, looks like a copy of existing oauth config section?

2026-01-01 10:46 UTC, electron0zero commented on config/config.go
> +	TLSConfig   *tls.Config            `yaml:"tls_config,omitempty"`
any reasons to not use `config.TLSConfig` in this case? we use that type across all probes so it's better to stay consistent with TLS config options we expose?

2026-01-01 10:46 UTC, electron0zero commented on config/config.go
> +	BearerToken string                 `yaml:"bearer_token,omitempty"`
This is a secret so you should be using Secret type from the common/config: https://github.com/prometheus/common/blob/d80d8544703e59a080a204b6f7429ac6561fb24f/config/config.go#L28

if you don't use Secret type in this case, the token will be logged by the logs and will be exposed in the config page.

2026-01-01 10:46 UTC, electron0zero commented on config/config.go
> +	HTTPHeaders map[string]interface{} `yaml:"headers,omitempty"`
please use https://github.com/prometheus/common/blob/main/config/headers.go

they have secret type, support for files and validation logic methods that you can reuse those.

see https://github.com/prometheus/common/blob/d80d8544703e59a080a204b6f7429ac6561fb24f/config/headers.go#L116 on how to build headers from all sources.

2026-01-01 10:46 UTC, electron0zero commented on config/config.go
> +	Password string `yaml:"password"`
password should be Secret type.

2026-01-01 10:46 UTC, electron0zero commented on config/config.go
> +	return "Basic " + base64.StdEncoding.EncodeToString([]byte(c.Username+":"+c.Password))
since we are converting the basic auth into a Header, do we need to support a basic auth? 

we can just document that they can use Basic Auth with headers and let users set this header by supported methods, including files, etc.

2026-01-03 09:32 UTC, bilkoua commented
@electron0zero Thanks
@adnull Could you make these fixes?

2026-01-19 14:31 UTC, bilkoua commented
@adnull any updates? Do you need any help with that?

2026-01-19 15:15 UTC, adnull commented
Hi, working on that, will update soon

2026-01-19 15:15 UTC, adnull commented
Hi, working on that, will update soon

2026-02-02 09:01 UTC, adnull commented
> @adnull any updates? 

finally got time to address that. Had to implement my own headers constructor to use with the prometheus.config.HTTPClientConfig. @electron0zero btw just found out the config documentation isn't up to date for http_probe with the real code (it uses HTTPClientConfig but the docs still don't reflect it still using basic_auth, etc.)

2026-02-02 09:20 UTC, bilkoua commented
@adnull Thank you very much. Could you also fix tests?

2026-02-02 09:25 UTC, adnull commented
> @adnull Thank you very much. Could you also fix tests?

Yep, just've fixed.

2026-02-02 10:42 UTC, bilkoua commented
@electron0zero Could you take a look at this PR after the changes?

2026-02-02 19:19 UTC, electron0zero commented on example.yml
> +        - expect: ^Welcome
nit: missing newline, please add.

2026-02-02 19:28 UTC, adnull commented on example.yml
> +        - expect: ^Welcome
ok np

2026-02-02 19:49 UTC, electron0zero commented on prober/websocket.go
> +		match := qr.Expect.Regexp.FindSubmatchIndex(message)
```suggestion
		match := qr.Expect.FindSubmatchIndex(message)
```

2026-02-02 19:49 UTC, electron0zero commented on prober/websocket.go
> +		send = string(qr.Expect.Regexp.Expand(nil, []byte(send), message, match))
```suggestion
		send = string(qr.Expect.Expand(nil, []byte(send), message, match))
```

2026-02-02 19:49 UTC, electron0zero commented on prober/websocket.go
> +		probeFailedDueToRegex := prometheus.NewGauge(prometheus.GaugeOpts{
should be move up top with other metrics and should not be under the if condition.

2026-02-02 19:49 UTC, electron0zero commented on prober/websocket.go
> +	})
the prober is missing `probe_websocket_duration_seconds` metric, please see code in http, tcp and other prober and add a metric that matchs those prober.

`duration_seconds` is a basic metric that you expect from your prober to know the latency of the probes you are running. in lots of the cases, you also care about latency along with probe pass/fail.

having phases would be useful as well because then it helps you narrow down where the time is going, so something to consider as well.

2026-02-02 19:49 UTC, electron0zero commented on prober/websocket.go
> +	dialer := websocket.Dialer{
we allow users to configure the ip protocal and fallback via `preferred_ip_protocol` and `ip_protocol_fallback` in other probers, please add the same for this prober as well.

users should be able to configure ipv4, ipv6, etc.

2026-02-02 19:49 UTC, electron0zero commented on config/config.go
> +	Headers          map[string]string       `yaml:"headers,omitempty"`
we should either use Headers type from https://github.com/prometheus/common/blob/28b645dd96866da2c1f6b2ba7acd9c7271732332/config/headers.go#L53 as it has support for paintext and secret headers both.

or you can make it a `map[string]Secret` so we don't leak the secrets in the UI and logs.

we are taking the config and building the headers so in most cases there headers will contain secrets.

2026-02-02 19:49 UTC, electron0zero commented on prober/websocket.go
> +	connection, resp, err := dialer.DialContext(ctx, targetURL.String(), constructHeadersFromConfig(module.Websocket, logger))
can we add `probe_websocket_ssl` if the connection is made over ssl, we have similar metrics in other probers so makes sense to follow the lead and expose these metrics.

2026-02-03 08:54 UTC, adnull commented on prober/websocket.go
> +	})
implemented

2026-02-03 08:58 UTC, adnull commented on prober/websocket.go
> +	connection, resp, err := dialer.DialContext(ctx, targetURL.String(), constructHeadersFromConfig(module.Websocket, logger))
Maybe we add it in another PR? Would be great to implement it together with the http probe by creating standart approach and not duplicate the code. Like we do smth like that
```
TLSMetrics := registerTLSMetrics(registry)
....
TLSMetrics.setFromConn(tls.Conn)
```

2026-02-03 09:03 UTC, adnull commented
@electron0zero could you take a look at the changes?

2026-02-03 09:27 UTC, bilkoua commented
@adnull Thanks, great work. Could you also take care of the DCO?

2026-02-03 10:33 UTC, adnull commented
@bilkoua thanks. done

2026-02-03 19:43 UTC, electron0zero commented on prober/websocket.go
> +	connection, resp, err := dialer.DialContext(ctx, targetURL.String(), constructHeadersFromConfig(module.Websocket, logger))
cool, I am good with follow up PR.

2026-02-03 19:50 UTC, electron0zero commented on go.mod
> +	golang.org/x/exp v0.0.0-20240506185415-9bf2ced13842 // indirect
bit confused by this? why are we pulling this? 

asking because https://pkg.go.dev/golang.org/x/exp#section-readme says following:

> This subrepository holds experimental and deprecated (in the old directory) packages.

we don't want both experimental and deprecated packages as dependency.

2026-02-03 19:52 UTC, electron0zero commented
we are almost there and ready to merge. 

can you rebase on master and added `websocket` as valid prober in the config.go, we merged https://github.com/prometheus/blackbox_exporter/pull/1521 and it adds validation for prober names.

2026-02-03 19:53 UTC, electron0zero commented on go.mod
> +	golang.org/x/exp v0.0.0-20240506185415-9bf2ced13842 // indirect
false alarm, I didn't notice that this was already there as an indirect dependency was just reordered.

2026-02-03 20:08 UTC, adnull commented
@electron0zero sure, seems completed.

2026-02-03 20:08 UTC, electron0zero commented on prober/websocket.go
> +				return true
we should return false here? or otherwise we will set `probe_success` to 0 instead of setting it to 1.

check `probeSuccessGauge` logic in the handler.go to understand how we use the returned value from the `Probers`

2026-02-03 20:09 UTC, electron0zero commented on prober/websocket.go
> +				return true
also, we should add a test case to make sure we don't regress. we can check for `probe_success` metric in tests to test this.

2026-02-03 20:12 UTC, adnull commented on prober/websocket.go
> +				return true
Do we consider the prober to be unsuccessfull in that case? As only a part of prober fails.

2026-02-03 20:16 UTC, electron0zero commented on config/config.go
> +	type plain WebsocketProbe
```suggestion
		*s = DefaultWebsocketProbe
		type plain WebsocketProbe
```

without this our default config won't be unmarshalled. we do the same in other probers as well.

2026-02-03 20:17 UTC, electron0zero commented on prober/websocket.go
> +	logger.Debug("Constructed headers", "headers", headers)
this log line will leak secrets, `headers` is a plain map here, if we need to log the headers, we should log the websocketConfig.Headers to make sure we don't leak secrets in logs.

2026-02-03 20:23 UTC, electron0zero commented on prober/websocket.go
> +				return true
yes, because our regex check didn't pass, the probe is considered failed.

think of like this: you expect `abc` from server so you configure a regex to check for it, but the server returned data, but it was not `abc`. so connection was successful, it returned data but not the data we expect.


Think of it like HTTP returning 200 but with wrong body, connection worked, but validation failed, which means that this is a probe failure.

check other probers for reference.

users use `probe_success` for alerting so if we don't return this, folks won't get alerts when the probe failed.

`probe_websocket_failed_due_to_regex` is more of a debugging metric to know why the probe failed.

2026-02-03 20:30 UTC, adnull commented on prober/websocket.go
> +	logger.Debug("Constructed headers", "headers", headers)
we don't need it

2026-02-03 20:33 UTC, adnull commented on prober/websocket.go
> +				return true
updated the code and tests

2026-02-03 21:09 UTC, electron0zero approved these changes
lgtm

2026-02-03 21:10 UTC, electron0zero commented
I will wait for few weeks to give time to other maintainers to review it.

2026-02-20 09:18 UTC, bilkoua commented
@electron0zero @mem @SuperQ Hi guys
Could you take a look at this PR and merging if all is fine? We’ve been waiting quite a while;)

2026-03-05 12:53 UTC, bilkoua commented
@electron0zero @mem @SuperQ ping

2026-03-05 15:18 UTC, merged

2026-03-06 08:56 UTC, bilkoua commented
@adnull @electron0zero Thanks, guys, for all your hard work - it’s finally here.
@electron0zero Would it be possible to ship a release so we can start using this functionality?

2026-08-06 06:38 UTC, veso0308 commented
Is it possible to bump a new version which includes the websocket prober?