Document difference between TLS Cert expiry metrics
prometheus/blackbox_exporter pull request #1330
Opened 2024-12-03 12:30 UTC by slrtbtfs

blackbox-exporter currently offers two metrics to
measure when TLS Certificates will expire.

The difference between those is very subtle, but
using `probe_ssl_earliest_cert_expiry`
for checking whether a certificate is due to
replacement can lead to false positive alerts.

This documents the difference between those two.

Generally, `probe_ssl_last_chain_expiry_timestamp_seconds`
 seems to be what most people would want to use.

2024-12-03 12:56 UTC, slrtbtfs commented
Hm, the CircleCI Tests seem to be failing for reasons unrelated to this PR:

```
level=error msg="Resolution with IP protocol failed" target=ipv6.google.com ip_protocol=ip4 err="lookup ipv6.google.com on 10.89.4.1:53: no such host"
```

Looks like the CI Test environment is having some network Issues.

Locally, the tests run fine.

2025-02-25 09:05 UTC, slrtbtfs commented
CI is passing now after a rebase, so this PR is ready.

2025-10-30 17:18 UTC, electron0zero commented on prober/prober.go
> +	helpSSLEarliestCertExpiry     = "Returns the earliest expiry of any peer certificate returned by the server as an unix timestamp. This can include certificates that are not validated by TLS clients.
this feels bit much for the help, can you trim it a bit and make it less verbose?

same for the example below.

if you wish to add more details, please add a section about SSL metrics in README.md to document these in details.

2025-11-28 11:45 UTC, slrtbtfs commented on prober/prober.go
> +	helpSSLEarliestCertExpiry     = "Returns the earliest expiry of any peer certificate returned by the server as an unix timestamp. This can include certificates that are not validated by TLS clients.
descriptions have been shortened now

2026-08-25 13:53 UTC, ArthurSens requested changes
Please remove the binary that you've included in this change

2026-09-17 18:18 UTC, ArthurSens commented
I'm taking the liberty of closing the PR since there have been no responses for a while. Feel free to open a new PR without the binary if you're still interested in making this change

2026-09-17 18:18 UTC, closed without merging